services:
  - type: web
    name: my-resume-api # Make sure this matches the service name you chose on Render
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false # This tells Render to use the value you already set in the dashboard
    build:
      packages:
        - libxml2-dev
        - libxslt-dev