services:
  - type: web
    name: my-resume-api # <-- IMPORTANT: Change this to your service name on Render
    env: python
    pythonVersion: "3.11" # Specifies a stable Python version
    plan: free
    build:
      packages:
        - libxml2-dev
        - libxslt-dev
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GEMINI_API_KEY
        sync: false # Tells Render to use the value from the dashboard
